run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  govet:
    check-type-assertions: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 3

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - gocyclo
        - errcheck

output:
  formats:
    - format: colored-line-number
