package output

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	dbdiff "github.com/meru143/dbdiff/internal/diff"
	"github.com/meru143/dbdiff/pkg/types"
)

// Format options
type FormatOptions struct {
	Format       string
	PrettyPrint  bool
	IncludeMeta  bool
	SourceDB     string
	TargetDB     string
	UseColors    bool
	IsExecutable bool // Add Executable output property
}

// Formatter handles output formatting
type Formatter struct {
	options      FormatOptions
	sourceSchema *types.Schema
}

// NewFormatter creates a new formatter
func NewFormatter(format string) *Formatter {
	return &Formatter{
		options: FormatOptions{
			Format:      format,
			PrettyPrint: true,
			IncludeMeta: true,
			UseColors:   isTTY(),
		},
		sourceSchema: nil,
	}
}

// NewFormatterWithOptions creates a formatter with custom options
func NewFormatterWithOptions(opts FormatOptions) *Formatter {
	opts.UseColors = opts.UseColors && isTTY()
	return &Formatter{options: opts, sourceSchema: nil}
}

// NewFormatterWithSchema creates a formatter with source schema for full SQL generation
func NewFormatterWithSchema(format string, sourceSchema *types.Schema) *Formatter {
	return &Formatter{
		options: FormatOptions{
			Format:      format,
			PrettyPrint: true,
			IncludeMeta: true,
			UseColors:   isTTY(),
		},
		sourceSchema: sourceSchema,
	}
}

// Format formats diffs based on configured format
func (f *Formatter) Format(diffs types.DiffList) (string, error) {
	switch f.options.Format {
	case "sql":
		if f.options.IsExecutable {
			return f.formatExecutable(diffs), nil
		}
		return f.formatSQL(diffs), nil
	case "table":
		return f.formatTable(diffs), nil
	case "json":
		return f.formatJSON(diffs), nil
	default:
		return f.formatSQL(diffs), nil
	}
}

// FormatMigration formats diffs as migration SQL
func (f *Formatter) FormatMigration(diffs types.DiffList, transaction bool) (string, error) {
	var sql string

	if f.options.IsExecutable {
		// Output the generated string without SQL BEGINs, since Bash will handle it natively
		sql = f.formatExecutable(diffs)
		return sql, nil
	}

	sql = f.formatSQL(diffs)
	if transaction {
		sql = "BEGIN;\n\n" + sql + "\n\nCOMMIT;"
	}
	return sql, nil
}

// formatSQL generates formatted SQL with comments and basic indentation
func (f *Formatter) formatSQL(diffs types.DiffList) string {
	var sb strings.Builder

	// Header comments
	if f.options.IncludeMeta {
		sb.WriteString("-- Generated by dbdiff\n")
		sb.WriteString(fmt.Sprintf("-- Timestamp: %s\n", time.Now().Format("2006-01-02 15:04:05")))
		if f.options.SourceDB != "" {
			sb.WriteString(fmt.Sprintf("-- Source: %s\n", f.options.SourceDB))
		}
		if f.options.TargetDB != "" {
			sb.WriteString(fmt.Sprintf("-- Target: %s\n", f.options.TargetDB))
		}
		sb.WriteString("\n")
	}

	for _, diff := range diffs {
		sb.WriteString(f.formatDiffComment(&diff))
		sb.WriteString(f.formatDiffSQL(&diff))
		sb.WriteString("\n")
	}

	return sb.String()
}

// formatExecutable generates an executable bash script wrapping the configured SQL
func (f *Formatter) formatExecutable(diffs types.DiffList) string {
	var sb strings.Builder

	// Write Bash shebang and error handling
	sb.WriteString("#!/bin/bash\n")
	sb.WriteString("set -e\n\n")

	sb.WriteString("# Generated by dbdiff\n")
	sb.WriteString(fmt.Sprintf("# Timestamp: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString("# This script will execute the migrations natively using psql.\n\n")

	sb.WriteString("DB_URL=${1:-$DATABASE_URL}\n")
	sb.WriteString("if [ -z \"$DB_URL\" ]; then\n")
	sb.WriteString("  echo \"Error: DATABASE_URL environment variable or argument is required.\"\n")
	sb.WriteString("  echo \"Usage: $0 [postgres://user:pass@host:port/db]\"\n")
	sb.WriteString("  exit 1\n")
	sb.WriteString("fi\n\n")

	sb.WriteString("echo \"Validating database connection...\"\n")
	sb.WriteString("if ! psql \"$DB_URL\" -c '\\q' >/dev/null 2>&1; then\n")
	sb.WriteString("  echo \"Error: Unable to connect to database at $DB_URL\"\n")
	sb.WriteString("  exit 1\n")
	sb.WriteString("fi\n\n")

	sb.WriteString("echo \"Applying migrations...\"\n")
	sb.WriteString("psql -v ON_ERROR_STOP=1 \"$DB_URL\" << 'EOF'\n")
	sb.WriteString("BEGIN;\n\n")

	// Embed the entire raw SQL inside the hermetic bash wrapper
	sql := f.formatSQL(diffs)
	sb.WriteString(sql)

	sb.WriteString("\nCOMMIT;\n")
	sb.WriteString("EOF\n\n")

	sb.WriteString("echo \"Migrations completed successfully!\"\n")

	return sb.String()
}

func (f *Formatter) formatDiffComment(diff *types.Diff) string {
	var sb strings.Builder

	switch diff.Object {
	case types.ObjectTable:
		switch diff.Type {
		case types.DiffAdd:
			sb.WriteString(fmt.Sprintf("-- Create table: %s\n", diff.Name))
		case types.DiffDrop:
			sb.WriteString(fmt.Sprintf("-- Drop table: %s\n", diff.Name))
		case types.DiffRename:
			sb.WriteString(fmt.Sprintf("-- Rename table: %s -> %s\n", diff.OldValue, diff.NewValue))
		}
	case types.ObjectColumn:
		switch diff.Type {
		case types.DiffAdd:
			sb.WriteString(fmt.Sprintf("-- Add column: %s to %s\n", diff.Name, diff.TableName))
		case types.DiffDrop:
			sb.WriteString(fmt.Sprintf("-- Drop column: %s from %s\n", diff.Name, diff.TableName))
		case types.DiffAlter:
			sb.WriteString(fmt.Sprintf("-- Alter column: %s.%s\n", diff.TableName, diff.Name))
		}
	case types.ObjectIndex:
		switch diff.Type {
		case types.DiffAdd:
			sb.WriteString(fmt.Sprintf("-- Create index: %s\n", diff.Name))
		case types.DiffDrop:
			sb.WriteString(fmt.Sprintf("-- Drop index: %s\n", diff.Name))
		case types.DiffAlter:
			sb.WriteString(fmt.Sprintf("-- Alter index: %s\n", diff.Name))
		}
	case types.ObjectConstraint:
		switch diff.Type {
		case types.DiffAdd:
			sb.WriteString(fmt.Sprintf("-- Add constraint: %s\n", diff.Name))
		case types.DiffDrop:
			sb.WriteString(fmt.Sprintf("-- Drop constraint: %s\n", diff.Name))
		case types.DiffAlter:
			sb.WriteString(fmt.Sprintf("-- Alter constraint: %s\n", diff.Name))
		}
	case types.ObjectForeignKey:
		switch diff.Type {
		case types.DiffAdd:
			sb.WriteString(fmt.Sprintf("-- Add foreign key: %s\n", diff.Name))
		case types.DiffDrop:
			sb.WriteString(fmt.Sprintf("-- Drop foreign key: %s\n", diff.Name))
		case types.DiffAlter:
			sb.WriteString(fmt.Sprintf("-- Alter foreign key: %s\n", diff.Name))
		}
	case types.ObjectSequence:
		switch diff.Type {
		case types.DiffAdd:
			sb.WriteString(fmt.Sprintf("-- Create sequence: %s\n", diff.Name))
		case types.DiffDrop:
			sb.WriteString(fmt.Sprintf("-- Drop sequence: %s\n", diff.Name))
		case types.DiffAlter:
			sb.WriteString(fmt.Sprintf("-- Alter sequence: %s\n", diff.Name))
		}
	case types.ObjectType:
		switch diff.Type {
		case types.DiffAdd:
			sb.WriteString(fmt.Sprintf("-- Create type: %s\n", diff.Name))
		case types.DiffDrop:
			sb.WriteString(fmt.Sprintf("-- Drop type: %s\n", diff.Name))
		}
	}

	// Add old/new values as comments
	if diff.Description != "" {
		sb.WriteString(fmt.Sprintf("-- %s\n", diff.Description))
	}
	if diff.OldValue != "" {
		sb.WriteString(fmt.Sprintf("-- Old: %s\n", diff.OldValue))
	}
	if diff.NewValue != "" {
		sb.WriteString(fmt.Sprintf("-- New: %s\n", diff.NewValue))
	}

	return sb.String()
}

func (f *Formatter) formatDiffSQL(diff *types.Diff) string {
	// Use SQLGenerator for proper SQL generation
	// Disable transaction wrapper since FormatMigration handles that
	var generator *dbdiff.SQLGenerator
	if f.sourceSchema != nil {
		generator = dbdiff.NewSQLGeneratorWithSchema(types.DiffList{*diff}, f.options.SourceDB, f.sourceSchema)
	} else {
		generator = dbdiff.NewSQLGenerator(types.DiffList{*diff}, f.options.SourceDB)
	}
	generator.SetTransaction(false)
	return generator.Generate()
}

// formatTable creates ASCII table output
func (f *Formatter) formatTable(diffs types.DiffList) string {
	var sb strings.Builder

	// Color codes
	green := "\033[32m"
	red := "\033[31m"
	yellow := "\033[33m"
	reset := "\033[0m"

	// Header
	sb.WriteString("\n")
	sb.WriteString("┌──────┬──────────┬──────────────┬───────────────┬────────────────────────────┐\n")
	sb.WriteString("│ Type │ Object   │ Name         │ Table         │ Details                    │\n")
	sb.WriteString("├──────┼──────────┼──────────────┼───────────────┼────────────────────────────┤\n")

	for _, diff := range diffs {
		details := ""
		if diff.OldValue != "" && diff.NewValue != "" {
			details = fmt.Sprintf("%s → %s", diff.OldValue, diff.NewValue)
		}

		typeStr := string(diff.Type)
		objStr := string(diff.Object)

		// Apply colors if enabled
		if f.options.UseColors {
			switch diff.Type {
			case types.DiffAdd:
				typeStr = green + typeStr + reset
			case types.DiffDrop:
				typeStr = red + typeStr + reset
			case types.DiffAlter:
				typeStr = yellow + typeStr + reset
			}
		}

		sb.WriteString(fmt.Sprintf("│ %-4s │ %-8s │ %-12s │ %-13s │ %-26s │\n",
			typeStr,
			objStr,
			truncate(diff.Name, 12),
			truncate(diff.TableName, 13),
			truncate(details, 26),
		))
	}
	sb.WriteString("└──────┴──────────┴──────────────┴───────────────┴────────────────────────────┘\n")

	return sb.String()
}

// formatJSON creates JSON output
func (f *Formatter) formatJSON(diffs types.DiffList) string {
	var output interface{}

	if f.options.IncludeMeta {
		// Wrap with metadata
		output = map[string]interface{}{
			"metadata": map[string]string{
				"timestamp":   time.Now().Format(time.RFC3339),
				"generatedBy": "dbdiff",
				"source":      f.options.SourceDB,
				"target":      f.options.TargetDB,
			},
			"diffs": diffs,
		}
	} else {
		output = diffs
	}

	var bytes []byte
	var err error
	if f.options.PrettyPrint {
		bytes, err = json.MarshalIndent(output, "", "  ")
	} else {
		bytes, err = json.Marshal(output)
	}

	if err != nil {
		return fmt.Sprintf(`{"error": "%v"}`, err)
	}

	return string(bytes)
}

// WriteFile writes content to a file
func WriteFile(path string, content string) error {
	// Create parent directories if needed
	if idx := strings.LastIndex(path, "/"); idx > 0 {
		dir := path[:idx]
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("failed to create directory: %w", err)
		}
	}

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}
	return nil
}

// isTTY checks if stdout is a terminal
func isTTY() bool {
	fi, err := os.Stdout.Stat()
	if err != nil {
		return false
	}
	return (fi.Mode() & os.ModeCharDevice) != 0
}

func truncate(s string, maxLen int) string {
	if len(s) > maxLen {
		return s[:maxLen-2] + ".."
	}
	if s == "" {
		return "-"
	}
	return s
}
